pool:
  vmImage: 'windows-latest'

trigger: none
pr: none

resources:
  pipelines:
  - pipeline: DnDGen.Infrastructure
    source: 'DnDGen.Infrastructure - Build'
    trigger: 
      branches:
      - main

jobs:

- deployment: Infrastructure_Nuget
  displayName: Deploy Infrastructure NuGet Package
  environment: Prod
  strategy:
    runOnce:
      deploy:
        steps:
        - task: NuGetCommand@2
          displayName: 'NuGet push'
          inputs:
            command: push
            packagesToPush: '$(Pipeline.Workspace)/**/DnDGen.Infrastructure.*.nupkg'
            nuGetFeedType: external
            publishFeedCredentials: NuGet.org
        - task: GitHubRelease@1
          displayName: 'GitHub release (create)'
          inputs:
            gitHubConnection: 'github.com_cidthecoatrack'
            assets: '$(Pipeline.Workspace)/**/DnDGen.Infrastructure.*.nupkg'
